name: flutter_todo_list
description: An application that allows user to add and save to-do items and record the item
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get: ^4.6.1
  shared_preferences: ^2.0.6
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

 
